#!/bin/sh
cd `dirname $0`
#../CloudMGn -n .:../src:../../../queueinglib $*
# for shared lib, use: opp_run -l ../src/CloudMGn -n .:../src $*
#opp_run -l ../libCloudMGn.so -l ../../../queueinglib/libqueueinglib.so -n .:../src:../../../queueinglib $*
export LD_LIBRARY_PATH="${omnetpp_root}/lib"
#export LD_LIBRARY_PATH=../../../lib
#echo "${omnetpp_root}/lib"
../out/gcc-release/src/Fog -n .:../src:../../queueinglib:.:../src -l ../../queueinglib/queueinglib $*
#ulimit -c unlimited
#../out/gcc-debug/src/Fog_dbg -n .:../src:../../queueinglib:.:../src -l ../../queueinglib/queueinglib $*
exit 0
