//
// Generated file, do not edit! Created by nedtool 5.4 from ProbeQuery.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __FOG_PROBEQUERY_M_H
#define __FOG_PROBEQUERY_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace fog {

/**
 * Class generated from <tt>ProbeQuery.msg:19</tt> by nedtool.
 * <pre>
 * //CREATO PER POTER AGGIUNGER LA INFO SULLA QUERYID
 * message ProbeQuery
 * {
 *     int queryId;
 *     int jobId;
 *     int appId;
 * }
 * </pre>
 */
class ProbeQuery : public ::omnetpp::cMessage
{
  protected:
    int queryId;
    int jobId;
    int appId;

  private:
    void copy(const ProbeQuery& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ProbeQuery&);

  public:
    ProbeQuery(const char *name=nullptr, short kind=0);
    ProbeQuery(const ProbeQuery& other);
    virtual ~ProbeQuery();
    ProbeQuery& operator=(const ProbeQuery& other);
    virtual ProbeQuery *dup() const override {return new ProbeQuery(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getQueryId() const;
    virtual void setQueryId(int queryId);
    virtual int getJobId() const;
    virtual void setJobId(int jobId);
    virtual int getAppId() const;
    virtual void setAppId(int appId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ProbeQuery& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ProbeQuery& obj) {obj.parsimUnpack(b);}

} // namespace fog

#endif // ifndef __FOG_PROBEQUERY_M_H

